### ISSUE TITLE
resize images

### ISSUE THREAD

**Issue by ruipcarvalho** [gavvvr/obsidian-imgur-plugin#11]
Request for the implementation of image resizing with syntax similar to:
`![image](https://i.imgur.com/L1FoYS5.jpg|100)`
so that the image is resized to 100x100 pixels.

Thanks!

**Comment by gavvvr** [comment]
@ruipcarvalho I just learned it was possible to resize Obsidian images pasted locally. Did not know that before.
I think what you are asking for is a feature request to Obsidian team to support resizing of remote images.

**Comment by ruipcarvalho** [comment]
hi,

I just realised I had the wrong syntax. It works if you use 
![image|100](https://i.imgur.com/L1FoYS5.jpg)

**Comment by gavvvr** [comment]
@ruipcarvalho cool, good to know! Another TIL about Markdown

**Comment by gavvvr** [comment]
Hey @ruipcarvalho 
I recently learned that besides setting image size in Markdown, you can actually get different sizes of an image from Imgur. Just add one of the letters to the end of your image id in URL: h, l, m, t, b, s.
You can learn more about it from here: https://meta.stackoverflow.com/a/253405/3581539
