### ISSUE TITLE
v 2.1.0 ??

### ISSUE THREAD

**Issue by menagerie198** [gavvvr/obsidian-imgur-plugin#16]
Obsidian (on desktop) says there is a new version (2.1.0), and update is failing. I also note there is no such update here.

**Comment by gavvvr** [comment]
![image](https://user-images.githubusercontent.com/1719646/132493745-10b979f9-34d7-4cff-b3f9-34e43e2c9232.png)

@menagerie198 sorry, the build job is stuck. While it could be successfully built on my PC, looks like on CI there are other dependencies versions and the build job simply hangs at the very end:
```
src/ImgurPlugin.ts → main.js...
created main.js in 1.9s
```

The build process does not exit after this.

So, I am aware of the problem and will solve it soon. Fortunately it does not break the existing 2.0.0.
