### ISSUE TITLE
M1 SAYS PLUGIN NOT SUPPORTED 

### ISSUE THREAD

**Issue by bstarnes007** [gavvvr/obsidian-imgur-plugin#17]
Not letting me install the plug in on a M1.

**Comment by gavvvr** [comment]
Hi @bstarnes007 
This sounds weird. The JavaScript should be platform-independent.
What error do you receive? 
I do not have M1 Mac to reproduce myself

**Comment by gavvvr** [comment]
@bstarnes007 I found [probably a similar issue](https://github.com/denolehov/obsidian-git/issues/109). Please make sure you are using a Desktop version of Obsidian app on your Mac

**Comment by bstarnes007** [comment]
@gavvvr I had the iOS version. Love the M1 but definitely have to watch that one. It works great now that I have Mac version
