### ISSUE TITLE
Drop/drag for WORD files into Obsidian may not work with imgur plugin enabled

### ISSUE THREAD

**Issue by martin2urban** [gavvvr/obsidian-imgur-plugin#24]
Using Obsidian v0.13.23 it is possible to drag MS Word files into notes. The files then get automatically uploaded and linked into the Obsidian vault. However, with the imgur plugin (v2.1.1) enabled  and setting:  confirm before upload = "disabled" I no longer can use this functionality.   If setting: confirm before upload ="enabled"  the  MS Word file upload to the Obsidian fault  works again.  Using right-right click imgur offers me to upload the file or paste locally although not an image file.
Perhaps a possible plugin conflict with Obsidian core functionality?

**Comment by ruipcarvalho** [comment]
I'm having the same problem: CTRL + drag and drop of a file on my hard drive in Obsidian creates a link to the file, but this doesn't work with the imgur plugin (v 2.1.1) enabled. Enabling the 'confirm before upload' works with drag&drop but not with CTRL+drag&drop (that is with files outside of the vault). This has made me disable the imgur plugin as the CTRL+drag&drop functionality in Obsidian is more important than the ability to upload images to imgur.
