### ISSUE TITLE
Paste locally failed

### ISSUE THREAD

**Issue by twio142** [gavvvr/obsidian-imgur-plugin#25]
Hello :)

I have the option 'confirm before upload' enabled. But when I paste a picture and manually select 'paste locally', it does not save the copied picture and return the image url, it does nothing. (Though the plugin *does* fulfil the uploading job properly.) Turning the plugin off makes it work again.

Any idea what the reason could be?

**Comment by gavvvr** [comment]
Hi @twio142. Thanks for reporting. Did it started to happen recently or it has always been the problem?

**Comment by twio142** [comment]
> Hi @twio142. Thanks for reporting. Did it started to happen recently or it has always been the problem?

Hello @gavvvr, sorry but that I don't know, I just recently started using this plugin...
