### ISSUE TITLE
[Feature Request]: Paste-able in Canvas note

### ISSUE THREAD

**Issue by Missionary2112** [gavvvr/obsidian-imgur-plugin#42]
Currently, Imgur Plugin can only work when images pasted in Obsidian note file not in Canvas file.
It would be great to create a note and paste an image there and it would work as it does in note file. 

I'm looking forwards to that. Thank you.

**Comment by gavvvr** [comment]
Just learned about the Canvas feature from your request. Contributions are welcomed.

My 1st idea is that there should be something like `canvas-paste` event, but I do not see any canvas-related events [the most recent published API](https://github.com/obsidianmd/obsidian-api/tree/38dd22168d2925086371bfc59e36fd9121527a39)

**Comment by stories-with-dice** [comment]
Hey!

I'd also be interested in this. I see the paste doesn't trigger the messagebox when I paste directly in the canvas.

However, if I first create a textbox (double click) and paste the image in that, I see that it is triggered, as I get the message box to confirm uploading to imgur. However, if I click confirm nothing happens.

**Comment by jcusimano** [comment]
> Hey!
> 
> I'd also be interested in this. I see the paste doesn't trigger the messagebox when I paste directly in the canvas.
> 
> However, if I first create a textbox (double click) and paste the image in that, I see that it is triggered, as I get the message box to confirm uploading to imgur. However, if I click confirm nothing happens.

Same here!
Also checked Imgur account after this (authenticated imgur upload) and the image was not uploaded. It would be great to enable this feature in canvas as images really enhances canvas notes!

**Comment by Regulate0723** [comment]
I'm searching for this feature as well

**Comment by gavvvr** [comment]
This is a top priority feature request.
Gonna implement it, when I will have a time.

**Comment by vvb0762** [comment]
> This is a top priority feature request. Gonna implement it, when I will have a time.

hey,may i ask how things are going after a year,i still can't paste and upload successfully in canvas,it pops up the upload option but when clicked on it doesn't respond,thanks anyway for your hard work on this development!

**Comment by gavvvr** [comment]
Hi @vvb0762

The implementation of this feature required me to dive into some internals of Obsidian, which are not publicly exposed and may change in the future. But I am happy to announce that the feature is finally available in [2.5.0 release](https://github.com/gavvvr/obsidian-imgur-plugin/releases/tag/2.5.0) of the plugin.
Check it out!
