### ISSUE TITLE
Uploading GIF images

### ISSUE THREAD

**Issue by gilsondev** [gavvvr/obsidian-imgur-plugin#6]
When paste a GIF image (generated with record screen for example), he is not uploaded.

**Comment by gavvvr** [comment]
Just tried, it gets pasted as static png🤔
Will try to fix this when I have time

Thank you for reporting, @gilsondev

**Comment by gavvvr** [comment]
Hi @gilsondev, I do not see a way to use clipboard for gifs. As far as I could understand during testing, if you copy a gif, it is [already non-gif in a clipboard](https://stackoverflow.com/a/14945981/3581539). It is a static png. 
Same for pdf on my Mac: If you copy pdf and then try to copy-paste, the result is a png image of first pdf page.

Good news is you can use drag-and-drop. Check out the 1.1.0

**Comment by gilsondev** [comment]
Hi @gavvvr i didn't know about this. Thanks for your search :)
