### ISSUE TITLE
I can't authenticate

### ISSUE THREAD

**Issue by h0pler** [gavvvr/obsidian-imgur-plugin#72]
I tried several times but couldn't do it.
![image](https://github.com/gavvvr/obsidian-imgur-plugin/assets/90015315/a301478f-1441-4732-8c4a-07aa98c17a9f)
As shown in the attached image, Not authenticated appears every time.
Clicking the button will redirect you to Imgur, hit 'Allow' and then return to Obsidian as normal.
The whole process is OK, but the app always says I'm not authenticated.

I'm using Windows 10.

**Comment by jkune5** [comment]
I have the same issue

**Comment by gavvvr** [comment]
Hi! Thank you for reporting.
Reproduced on fresh Windows and macOS VMs.

No idea what could be wrong though... There are no errors in dev console and there are [not much changes](https://github.com/gavvvr/obsidian-imgur-plugin/compare/0b6f31ab..137c0f1) in source code in 2024. My last successful authentication happened on January on clean macOS. Will try to debug later.

**Comment by tadaspetra** [comment]
Can't authenticate either, happy to see there's an update coming today :)

**Comment by poisonoff** [comment]
I have the same issue (MacOS), and I tried both on Chrome and Safari, it didnt work out :(
