### ISSUE TITLE
Link to imgur albums from settings isn't correct

### ISSUE THREAD

**Issue by mtzfox** [gavvvr/obsidian-imgur-plugin#74]
Hi, I think imgur may have changed the format of their albums page, because the link in settings is going to a broken page. The app settings say:

> Manage your albums at https://myusername.imgur.com/all

But the working link is actually https://imgur.com/user/myusername

I'm pretty sure I've used the link before, so maybe they changed their URL format for user 'all' category.

A possibly related issue: I've also gotten a few errors recently after pasting that 'imgur upload failed' which seemed to go away after resetting Obsidian, but it's happened on both my MAC and PC, with the console listing a blocked resource. Not sure if this is related to imgur changing their user albums URLs (I dearly hope not) or just a personal cross-device settings issue with my work PC, but just thought I'd mention if it helps. If I see it much again, I'll add another issue.

Thank you!!

**Comment by gavvvr** [comment]
Hi @mtzfox 

The url for albums is correct.
It opens something like:
<img width="500" alt="image" src="https://github.com/gavvvr/obsidian-imgur-plugin/assets/1719646/0662e6a5-dd1f-4eaf-9887-64c0c0089ba4">
Where you will get a list of albums if you click on a drop down element saying "All images".

The temporary issues with uploading images ("imgur upload failed") happen from time to time, but there is nothing I can do about them. I am going to close this one, but I hope to hear if albums URL work the same way for you as it does for me.

**Comment by mtzfox** [comment]
Sorry, I realized it was an issue with being signed out of imgur due to VPN. Thanks for checking on this.
