### ISSUE TITLE
Cannot upload images. Imgur upload failed: Too Many Requests

### ISSUE THREAD

**Issue by nicolnt** [gavvvr/obsidian-imgur-plugin#80]
I get this error since today, it's the first time. I didn't upload anything until now.

```xml
<!--⚠️Imgur upload failed, check dev console-->
```

- Tried with different images to see
- Tried disconnection and reconnecting the plugin to Imgur
- Tried in Sandbox vault with obsidian-imgur-plugin being the only community plugin installed

Error message in dev console:
```
Failed imgur request:  Error: {"errors":[{"id":"legacy-api-7455b9c768-9f4v2/MdBem2HsQl-534732","code":"429","status":"Too Many Requests","detail":"Too Many Requests"}]}

    at handleImgurErrorResponse (plugin:obsidian-imgur-plugin:506:9)
    at AuthenticatedImgurClient.upload (plugin:obsidian-imgur-plugin:541:7)
    at async ImgurAuthenticatedUploader.upload (plugin:obsidian-imgur-plugin:609:13)
    at async _ImgurPlugin.uploadFileAndEmbedImgurImage (plugin:obsidian-imgur-plugin:1109:16)
uploadFileAndEmbedImgurImage @ plugin:obsidian-imgur-plugin:1117
```

```
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.5.3
	Operating system: Windows 10 Pro 10.0.19045
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Things v2.1.20
	Snippets enabled: 6
	Restricted mode: off
	Plugins installed: 38
	Plugins enabled: 29
		...
		23: Imgur v2.5.2
		...

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

```

**Comment by ottozhao-void** [comment]
Yes, Exactly, I also encountered this problem started yesterday. Just about to start a new issue and saw your issue.
The anonymous upload will work however.

**Comment by Maurilio97-P** [comment]
Same :(

![image](https://github.com/user-attachments/assets/43b7f5b2-5396-45e8-821f-d17e42fa09ff)

**Comment by gavvvr** [comment]
Thanks for your reports guys. Just checked my Obsidian running for weeks without restart (hence no updates received from Obsidian), and it's the same error for me now :( Tried to re-authenticate, but that didn't help.
It's interesting that there is some `legacy-api` substring mentioned in 429 response payload. I don't know how it can be "legacy", if the plugin is using the most recent v3 API 🤷‍♂️:

https://github.com/gavvvr/obsidian-imgur-plugin/blob/5fb18aa8929435a792f87aa99f4da898a5d1406d/src/imgur/constants.ts#L2

I guess it's a temporary problem on the Imgur API side and I hope it will be resolved soon.

**Comment by jmatos-sfdc** [comment]
Same issue here!  Hope it gets fixed soon!

**Comment by SteveZhengMe** [comment]
I got an 503 error.
![image](https://github.com/user-attachments/assets/faad1fee-d7e2-4985-830c-6e3f43da5358)

**Comment by jkune5** [comment]
I'm getting the same errors

```

plugin:obsidian-imgur-plugin:1117 Failed imgur request:  Error: {"errors":[{"id":"legacy-api-b87bc55bd-pkm29/dCdpVERlyK-523205","code":"429","status":"Too Many Requests","detail":"Too Many Requests"}]}

    at handleImgurErrorResponse (plugin:obsidian-imgur-plugin:506:9)
    at AuthenticatedImgurClient.upload (plugin:obsidian-imgur-plugin:541:7)
    at async ImgurAuthenticatedUploader.upload (plugin:obsidian-imgur-plugin:609:13)
    at async _ImgurPlugin.uploadFileAndEmbedImgurImage (plugin:obsidian-imgur-plugin:1109:16)
```

I got this error yesterday 

```
plugin:obsidian-imgur-plugin:1117 Failed imgur request:  Error: 
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 client read error</title>
  </head>
  <body>
    <h1>Error 503 client read error</h1>
    <p>client read error</p>
    <h3>Error 54113</h3>
    <p>Details: cache-lax-kwhp1940052-LAX 1721718602 1885401409</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>

    at handleImgurErrorResponse (plugin:obsidian-imgur-plugin:506:9)
    at AuthenticatedImgurClient.upload (plugin:obsidian-imgur-plugin:541:7)
    at async ImgurAuthenticatedUploader.upload (plugin:obsidian-imgur-plugin:609:13)
    at async _ImgurPlugin.uploadFileAndEmbedImgurImage (plugin:obsidian-imgur-plugin:1109:16)
uploadFileAndEmbedImgurImage	@	plugin:obsidian-imgur-plugin:1117
```

**Comment by madhex** [comment]
I believe your plugin just got too popular. We are sharing the same Client ID and according to the [documentation](https://apidocs.imgur.com/#:~:text=Rate%20Limits) *"Each application can allow approximately 1,250 uploads per day or approximately 12,500 requests per day."*

And here are some headers from my responses
```
x-post-rate-limit-limit: 1250
x-post-rate-limit-remaining: 1240
x-post-rate-limit-reset: 2699
x-ratelimit-clientlimit: 12500  <---
x-ratelimit-clientremaining: 0  <---
x-ratelimit-clientreset: 86400
x-ratelimit-userlimit: 500
x-ratelimit-userremaining: 499
x-ratelimit-userreset: 3600
```

**Comment by madhex** [comment]
I believe your plugin just got too popular. We are sharing the same Client ID and according to the [documentation](https://apidocs.imgur.com/#:~:text=Rate%20Limits) *"Each application can allow approximately 1,250 uploads per day or approximately 12,500 requests per day."*

And here are some headers from my responses
```
x-post-rate-limit-limit: 1250
x-post-rate-limit-remaining: 1240
x-post-rate-limit-reset: 2699
x-ratelimit-clientlimit: 12500
x-ratelimit-clientremaining: 0  <---
x-ratelimit-clientreset: 86400
x-ratelimit-userlimit: 500
x-ratelimit-userremaining: 499
x-ratelimit-userreset: 3600
```

**Comment by gavvvr** [comment]
@madhex That could be the reason...

My first thought was that it's not possible, because Client ID is used only by anonymous uploads strategy, but it turned out that it's also used by authenticated uploads when you perform OAuth authentication. Currently the shared Client Id is built into the URL opened by your browser:

https://github.com/gavvvr/obsidian-imgur-plugin/blob/090d8b88a134e0b919b4ba4133c4f010c758be87/src/ui/ImgurAuthModal.ts#L23

Ok, then the fix would be for every user to go to https://imgur.com/account/settings/apps and create their own ClientId

**Comment by proxium** [comment]
@gavvvr I confirm that the anonymous upload works (I added my own application Client ID). However, it's not recommended to upload pictures anonymously because the retention period will be shorter than using the authenticated upload feature.

Source: [Imgur-Terms-of-Service-Update](https://help.imgur.com/hc/en-us/articles/26479362527771-Imgur-Terms-of-Service-Update)

**Comment by jmatos-sfdc** [comment]
I don't think I'll be using this plug-in anymore.

**Comment by nicolnt** [comment]
> I don't think I'll be using this plug-in anymore.

Please comment to bring valuable information toward the resolution of the issue, not just put unnecessary pressure on the developer.

**Comment by grodax** [comment]
> @madhex That could be the reason...
> 
> My first thought was that it's not possible, because Client ID is used only by anonymous uploads strategy, but it turned out that it's also used by authenticated uploads when you perform OAuth authentication. Currently the shared Client Id is built into the URL opened by your browser:
> 
> https://github.com/gavvvr/obsidian-imgur-plugin/blob/090d8b88a134e0b919b4ba4133c4f010c758be87/src/ui/ImgurAuthModal.ts#L23
> 
> Ok, then the fix would be for every user to go to https://imgur.com/account/settings/apps and create their own ClientId

And what to do with the generated new ClientID?

**Comment by jmatos-sfdc** [comment]
I think you can use it only for anonymous uploads - go to the Imgur plugin settings and change the "Images upload approach" to "Anonmyous Imgur upload".  A text box will appear where you can enter the Client ID.

**Comment by softlylove** [comment]
<img width="544" alt="image" src="https://github.com/user-attachments/assets/657903fc-5a85-489d-a981-0832874b7aa7">

I'm having the same issue today :(

> I think you can use it only for anonymous uploads - go to the Imgur plugin settings and change the "Images upload approach" to "Anonmyous Imgur upload". A text box will appear where you can enter the Client ID.

For Anonymous content, Imgur may delete the contents in one day.

**Comment by nicolnt** [comment]
For your information, after updating and following the instructions [here](https://github.com/gavvvr/obsidian-imgur-plugin?tab=readme-ov-file#generating-client-id), I had to log out then log back in from the plugin settings for being able to upload again to Imgur.

Thanks for the prompt fix @gavvvr <3

**Comment by gavvvr** [comment]
> I believe your plugin just got too popular.

@madhex you were right, this issue was caused by shared Client ID into the source code:

https://github.com/gavvvr/obsidian-imgur-plugin/blob/5fb18aa8929435a792f87aa99f4da898a5d1406d/src/imgur/constants.ts#L1

There is one interesting observation: you can basically provide any value to Client ID (e.g. `a` or `test`, or even empty string) and it will work fine for anonymous uploads. It only won't work if you will try to reuse an old shared Client ID from above.
Feels like it caught monthly or even permanent rate-limiting ban.

---

I've updated the plugin and now each user is enforced to create his own Client ID. No more shared Client ID built into the plugin's source code. Users are now required to get one even for "Anonymous" uploads. You will see the link for detailed instructions in Imgur plugin settings tab in your Obsidian. As @nicolnt mentioned, don't forget to Logout/Login again, to get fresh authentication with a new Client ID.


---

Also, use the new feature to upload existing local images (for example, the ones, which failed to upload because of this bug) with a right-click context menu. It's a not yet 100% finished feature, because it won't remove local file after converting it to remote one, but I've decided to release it anyway since its already in `main` branch.

**Comment by gavvvr** [comment]
@madhex how did you get response headers? After switching to internal http client (72db49b76ee2395358ce04f85566ca2bfbeed096), I don't see any requests/responses in Obsidian's Chrome DevTools

**Comment by jkune5** [comment]
Big thanks to the developer for taking his time to fix this bug

**Comment by madhex** [comment]
> @madhex how did you get response headers? After switching to internal http client ([72db49b](https://github.com/gavvvr/obsidian-imgur-plugin/commit/72db49b76ee2395358ce04f85566ca2bfbeed096)), I don't see any requests/responses in Obsidian's Chrome DevTools

Me too. I used Fiddler. But you can also access them via the `resp.headers` property here

https://github.com/gavvvr/obsidian-imgur-plugin/blob/286431937b7b62169abdded83ffc833bc86d34a8/src/uploader/imgur/ImgurAnonymousUploader.ts#L27

**Comment by jmatos-sfdc** [comment]
Thanks for fixing this!

**Comment by SteveZhengMe** [comment]
the issue is solved by the new version. Thank you!!

**Comment by siddiqkaithodu** [comment]
Is this issue Fixed? I am having this
![image](https://github.com/user-attachments/assets/7655c0a3-73a9-4da1-9a3f-f5c019e8ec6e)
