### ISSUE TITLE
Error: ⚠️Imgur upload failed, check dev console

### ISSUE THREAD

**Issue by reggybsr** [gavvvr/obsidian-imgur-plugin#9]
I did everything I needed to do to get the plugin working, but the error still pops up. Why? (I'm not that big of a tech nerd so I don't understand that well, sorry)

**Comment by gavvvr** [comment]
@reggybsr, I am almost sure it fails for the same reason as #8 (check it out, it was reported today too. The problem can appear and disappear, so you can just try again and there are chances it will work)

If it still fails to you, could you please open the developer console (Ctrl/Cmd+Shift+I) and report here the response code and headers of a failed request on a **Network** tab? The failed one is usually marked with red.
![image](https://user-images.githubusercontent.com/1719646/118856905-1d60cb80-b8e0-11eb-8013-421d1851c599.png)

**Comment by reggybsr** [comment]
@gavvvr here's the headers and response code for one of the failed images. it says it failed to load the response code for every image, though.

![image](https://user-images.githubusercontent.com/84466946/118911095-360cc800-b958-11eb-95d8-5ecc90eb69df.png)

![image](https://user-images.githubusercontent.com/84466946/118911106-3efd9980-b958-11eb-8fc1-5db603cb53b0.png)

**Comment by gavvvr** [comment]
@reggybsr I do not see response headers here. You probably show the POST request here. If the first one (CORS with http method OPTIONS) failed, the original request does even attempt to be executed. There are 4 failed requests on your screenshot while I guess you only pasted twice.

But I just noticed you exposed your client_id. I recommend you to invalidate it and create a new one.
Btw the next time you face an issue with upload, you can check the API status at https://status.imgur.com/. It will probably show a global failure.

**Comment by ih8snow** [comment]
I have a similar problem,
does this info help?
Dataview Plugin - Version 0.3.x Loaded
main.ts:30 Loading Note Refactor plugin
main.ts:10 Loading Hotkeys++ plugin
main.ts:23 Image in Editor Plugin is loaded
main.ts:7 loading wikilinks-to-mdlinks plugin...
index.ts:317 Dataview: Parsed all file prefixes (0.001s)
index.ts:182 Dataview task & metadata indices prepared in 3.964s.
main.ts:35 Dataview: Version 0.3.x Loaded
index.ts:338 Dataview: Parsed all file prefixes (0.002s)
index.ts:200 Dataview: Task & metadata parsing queued in 0s.
index.html:1 Access to fetch at 'https://api.imgur.com/3/image.json' from origin 'app://obsidian.md' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
api.imgur.com/3/image.json:1 Failed to load resource: net::ERR_FAILED
main.ts:147 Failed imgur request:  TypeError: Failed to fetch
handleFailedUpload @ main.ts:147

**Comment by gavvvr** [comment]
@ih8snow, thanks for adding error log. It confirms that all users face the same problem with CORS sometimes which simply disappears later. And I also faced it once.

What I could do is to fall back to default paste of a file to vault. Just released 1.2.0, closing the issue

**Comment by candideu** [comment]
I ran into this issue today: 
![image](https://github.com/user-attachments/assets/0cfcac67-bb9e-4c0e-b55b-70d905bfd167)

**Comment by thammawat-s** [comment]
I have similar error today.
![image](https://github.com/user-attachments/assets/bd0aa385-820a-4312-ab7d-c3c58298cd7f)

**Comment by gavvvr** [comment]
@candideu @thammawat-s there was a global issue affecting everyone (#80). Update the plugin to 2.6.0 and follow new instructions to generate your own Client ID. The plugin should be fixed now. Leave a "thumbs up" reaction, if the update to 2.6.0 fixes your problems.

**Comment by ekozero** [comment]
Does thsi mean we can't use the authenticated option? I was hoping it could be fixed as it also serves as back up option for me to download all images under my account if things went south.

**Comment by candideu** [comment]
@gavvvr Thank you!
